import {Grid,Typography,Paper,TextField,Button,Box} from '@mui/material'
import {useForm,useFormState} from 'react-hook-form'
import {yupResolver} from '@hookform/resolvers/yup'
import * as yup from 'yup'
import axios from 'axios'
import {ColorRing} from 'react-loader-spinner'
import {useContext,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {UserContext} from '../App'
import Cookies from 'js-cookie'